#!/usr/bin/env bash
# install.sh — Bootstrap pragma into a target repository
#
# Usage:
#   pragma/install.sh [--agent] [/path/to/target-repo]
#
# Options:
#   --agent    Non-interactive mode (auto-install tools, no prompts)
#
# If no target repo is specified, uses the current directory.
set -euo pipefail

PRAGMA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$PRAGMA_DIR/lib/common.sh"

# ─── Parse arguments ─────────────────────────────────────────────────────────

AGENT_MODE=false
TARGET_REPO=""

for arg in "$@"; do
  case "$arg" in
    --agent) AGENT_MODE=true ;;
    *)       TARGET_REPO="$arg" ;;
  esac
done

TARGET_REPO="${TARGET_REPO:-.}"
TARGET_REPO="$(cd "$TARGET_REPO" && pwd)"

# ─── Validation ───────────────────────────────────────────────────────────────

if [[ ! -d "$TARGET_REPO/.git" ]]; then
  log_error "$TARGET_REPO is not a git repository"
  exit 1
fi

# Add pragma/bin to PATH if it exists (extracted Docker tools)
if [[ -d "$PRAGMA_DIR/bin" ]]; then
  export PATH="$PRAGMA_DIR/bin:$PATH"
fi

# Add GOPATH/bin to PATH so go-installed tools are found
_gobin="${GOBIN:-$(go env GOBIN 2>/dev/null)}"
_gobin="${_gobin:-$(go env GOPATH 2>/dev/null)/bin}"
_gobin="${_gobin:-$HOME/go/bin}"
if [[ -d "$_gobin" ]] && [[ ":$PATH:" != *":$_gobin:"* ]]; then
  export PATH="$_gobin:$PATH"
fi
unset _gobin

log_header "Pragma Setup"
log_info "Pragma dir: ${BOLD}$PRAGMA_DIR${RESET}"
log_info "Target repo:   ${BOLD}$TARGET_REPO${RESET}"
log_info "Mode:          ${BOLD}$(if $AGENT_MODE; then echo "agent (non-interactive)"; else echo "interactive"; fi)${RESET}"
echo ""

# ─── Step 1: Install lefthook if needed ───────────────────────────────────────

if ! has_tool lefthook; then
  log_warn "lefthook is not installed"

  if $AGENT_MODE; then
    log_info "Installing lefthook..."
    if has_tool go; then
      go install github.com/evilmartians/lefthook@latest
    elif has_tool nix-env; then
      nix-env -iA nixpkgs.lefthook
    else
      log_error "Cannot install lefthook: no go or nix available"
      log_info "Install manually: https://github.com/evilmartians/lefthook/blob/master/docs/install.md"
      exit 1
    fi
  else
    log_info "Install lefthook via one of:"
    echo "  go install github.com/evilmartians/lefthook@latest"
    echo "  nix-env -iA nixpkgs.lefthook"
    echo "  brew install lefthook"
    echo ""
    read -rp "Attempt auto-install via go? [Y/n] " answer
    if [[ ! "$answer" =~ ^[Nn] ]]; then
      go install github.com/evilmartians/lefthook@latest || {
        log_error "Failed to install lefthook"
        exit 1
      }
    else
      log_error "lefthook is required. Please install and re-run."
      exit 1
    fi
  fi

  # Ensure GOPATH/bin is in PATH so we can find the just-installed binary
  GOBIN_DIR="${GOBIN:-$(go env GOBIN 2>/dev/null)}"
  GOBIN_DIR="${GOBIN_DIR:-$(go env GOPATH 2>/dev/null)/bin}"
  GOBIN_DIR="${GOBIN_DIR:-$HOME/go/bin}"
  if [[ -d "$GOBIN_DIR" ]] && [[ ":$PATH:" != *":$GOBIN_DIR:"* ]]; then
    export PATH="$GOBIN_DIR:$PATH"
    hash -r 2>/dev/null || true
  fi

  if has_tool lefthook; then
    log_success "lefthook installed"
  else
    log_error "lefthook installation failed"
    exit 1
  fi
else
  log_success "lefthook is available ($(lefthook version 2>/dev/null || echo 'unknown version'))"
fi

# ─── Step 2: Generate lefthook.yml in target repo ────────────────────────────

LEFTHOOK_CONFIG="$TARGET_REPO/lefthook.yml"

generate_config() {
  cat > "$LEFTHOOK_CONFIG" << YAML
# Generated by pragma — https://github.com/zakstak/pragma
# To regenerate: $PRAGMA_DIR/install.sh $TARGET_REPO

pre-commit:
  parallel: true
  commands:
    format:
      glob: "*.{go,rs,ts,tsx,js,jsx,html,htm,yml,yaml,sh,md,toml,json,py}"
      run: $PRAGMA_DIR/lib/format.sh {staged_files}

    lint:
      glob: "*.{go,rs,ts,tsx,js,jsx,yml,yaml,sh,toml,py}"
      run: $PRAGMA_DIR/lib/lint.sh {staged_files}

    gitleaks:
      run: gitleaks protect --staged --redact
      skip:
        - merge
        - rebase

pre-push:
  commands:
    test:
      run: $PRAGMA_DIR/lib/test.sh
YAML
}

if [[ -f "$LEFTHOOK_CONFIG" ]]; then
  if $AGENT_MODE; then
    log_info "Overwriting existing lefthook.yml"
    generate_config
  else
    log_warn "lefthook.yml already exists in target repo"
    read -rp "Overwrite? [y/N] " answer
    if [[ "$answer" =~ ^[Yy] ]]; then
      generate_config
    else
      log_info "Keeping existing lefthook.yml"
    fi
  fi
else
  generate_config
fi

log_success "lefthook.yml written to $LEFTHOOK_CONFIG"

# ─── Step 3: Copy gitleaks config if target doesn't have one ──────────────────

if [[ ! -f "$TARGET_REPO/.gitleaks.toml" ]]; then
  cp "$PRAGMA_DIR/.gitleaks.toml" "$TARGET_REPO/.gitleaks.toml"
  log_success "Copied default .gitleaks.toml"
else
  log_skip "Target repo already has .gitleaks.toml"
fi

# ─── Step 4: Run lefthook install ─────────────────────────────────────────────

log_info "Installing git hooks via lefthook..."
(cd "$TARGET_REPO" && lefthook install) || {
  log_error "lefthook install failed"
  exit 1
}
log_success "Git hooks installed"

# ─── Step 5: Install required tools ───────────────────────────────────────────

echo ""
if $AGENT_MODE; then
  "$PRAGMA_DIR/tools/install-tools.sh" --agent
else
  "$PRAGMA_DIR/tools/install-tools.sh"
fi

# ─── Done ─────────────────────────────────────────────────────────────────────

echo ""
log_header "Setup Complete"
log_success "Pragma is configured for ${BOLD}$TARGET_REPO${RESET}"
echo ""
log_info "Hooks installed:"
echo "  ${GREEN}pre-commit${RESET} → format + lint + gitleaks"
echo "  ${GREEN}pre-push${RESET}   → tests"
echo ""
log_info "To skip hooks temporarily:"
echo "  git commit --no-verify"
echo "  git push --no-verify"
echo ""
log_info "To uninstall:"
echo "  cd $TARGET_REPO && lefthook uninstall"
